### PR TITLE
Fix compatibility with Plasma 6

### LINKED ISSUE #401: Doesn't work with Plasma 6 alpha because lack "KPackageStructure": "KWin/Effect" in metadata.json
## Describe the Bug

Plasma seem change some requirements in Plasma 6. When I try to use this project in Plasma 6, I got some errors:
```
Nov 19 20:44:23 kwin_wayland[1795]: KPackageStructure of KPluginMetaData(pluginId:"kwin4_effect_energize_a", fileName: "/usr/share/kwin/effects/kwin4_effect_energize_a/metadata.json") does not match requested format "KWin/Effect"
Nov 19 20:44:23 kwin_wayland[1795]: KPackageStructure of KPluginMetaData(pluginId:"kwin4_effect_energize_b", fileName: "/usr/share/kwin/effects/kwin4_effect_energize_b/metadata.json") does not match requested format "KWin/Effect"
Nov 19 20:44:23 kwin_wayland[1795]: KPackageStructure of KPluginMetaData(pluginId:"kwin4_effect_fire", fileName: "/usr/share/kwin/effects/kwin4_effect_fire/metadata.json") does not match requested format "KWin/Effect"
Nov 19 20:44:23 kwin_wayland[1795]: KPackageStructure of KPluginMetaData(pluginId:"kwin4_effect_hexagon", fileName: "/usr/share/kwin/effects/kwin4_effect_hexagon/metadata.json") does not match requested format "KWin/Effect"
Nov 19 20:44:23 kwin_wayland[1795]: KPackageStructure of KPluginMetaData(pluginId:"kwin4_effect_incinerate", fileName: "/usr/share/kwin/effects/kwin4_effect_incinerate/metadata.json") does not match requested format "KWin/Effect"
Nov 19 20:44:23 kwin_wayland[1795]: KPackageStructure of KPluginMetaData(pluginId:"kwin4_effect_tv", fileName: "/usr/share/kwin/effects/kwin4_effect_tv/metadata.json") does not match requested format "KWin/Effect"
Nov 19 20:44:23 kwin_wayland[1795]: KPackageStructure of KPluginMetaData(pluginId:"kwin4_effect_wisps", fileName: "/usr/share/kwin/effects/kwin4_effect_wisps/metadata.json") does not match requested format "KWin/Effect"
Nov 19 20:44:23 kwin_wayland[1795]: KPackageStructure of KPluginMetaData(pluginId:"kwin4_effect_doom", fileName: "/usr/share/kwin/effects/kwin4_effect_doom/metadata.json") does not match requested format "KWin/Effect"
Nov 19 20:44:23 kwin_wayland[1795]: KPackageStructure of KPluginMetaData(pluginId:"kwin4_effect_pixel_wheel", fileName: "/usr/share/kwin/effects/kwin4_effect_pixel_wheel/metadata.json") does not match requested format "KWin/Effect"
Nov 19 20:44:23 kwin_wayland[1795]: KPackageStructure of KPluginMetaData(pluginId:"kwin4_effect_pixel_wipe", fileName: "/usr/share/kwin/effects/kwin4_effect_pixel_wipe/metadata.json") does not match requested format "KWin/Effect"
Nov 19 20:44:23 kwin_wayland[1795]: KPackageStructure of KPluginMetaData(pluginId:"kwin4_effect_pixelate", fileName: "/usr/share/kwin/effects/kwin4_effect_pixelate/metadata.json") does not match requested format "KWin/Effect"
Nov 19 20:44:23 kwin_wayland[1795]: KPackageStructure of KPluginMetaData(pluginId:"kwin4_effect_glide", fileName: "/usr/share/kwin/effects/kwin4_effect_glide/metadata.json") does not match requested format "KWin/Effect"
Nov 19 20:44:23 kwin_wayland[1795]: KPackageStructure of KPluginMetaData(pluginId:"kwin4_effect_glitch", fileName: "/usr/share/kwin/effects/kwin4_effect_glitch/metadata.json") does not match requested format "KWin/Effect"
Nov 19 20:44:23 kwin_wayland[1795]: KPackageStructure of KPluginMetaData(pluginId:"kwin4_effect_portal", fileName: "/usr/share/kwin/effects/kwin4_effect_portal/metadata.json") does not match requested format "KWin/Effect"
Nov 19 20:44:23 kwin_wayland[1795]: KPackageStructure of KPluginMetaData(pluginId:"kwin4_effect_tv_glitch", fileName: "/usr/share/kwin/effects/kwin4_effect_tv_glitch/metadata.json") does not match requested format "KWin/Effect"
```

That's because we lack `"KPackageStructure": "KWin/Effect",` in metadata.json. When I added it, the problem disappeared.

## System
_Please complete the following information:_
 - Linux distribution Arch Linux
 - Burn-My-Windows version https://github.com/Schneegans/Burn-My-Windows/commit/6d7d6326b4ebe3bf26de235247458aa917ff1076
 - Plasma version: 6 alpha

### PR DESCRIPTION
**Pull request by CoelacanthusHex**
New requirement in Plasma 6.
resolve #401

### CODE REVIEW

**Comment by CoelacanthusHex** [comment]
I think CI failure is unrelated because has the same failure and my PR only changed the kwin part.

**Comment by Schneegans** [comment]
Hi there! Thanks a lot! The CI fail is indeed unrelated. The rawhide check is not 100% deterministic, it fails sometimes :smile:. Do you know whether this change is backwards-compatible to Plasma 5.x?

**Comment by CoelacanthusHex** [comment]
> Hi there! Thanks a lot! The CI fail is indeed unrelated. The rawhide check is not 100% deterministic, it fails sometimes 😄. Do you know whether this change is backwards-compatible to Plasma 5.x?

My friend @KunoiSayami confirmed it also works on Plasma 5.x.

**Comment by Schneegans** [comment]
Ok, thanks a lot! I'll add a changelog entry and test this on my end before releasing it.

**Pull request merged**
